---
- name: service | mariadb | started
  service:
    name: mysql
    state: started

- name: service | mariadb | stopped
  service:
    name: mysql
    state: stopped

- name: service | mariadb | restarted
  service:
    name: mysql
    state: restarted

- name: service | mariadb | reloaded
  service:
    name: mysql
    state: reloaded
