---
- include: cleanup.yml
- include: install.yml
- { include: configure.yml,  when: mariadb_server }
- { include: logging.yml,    when: mariadb_server }
- { include: backup.yml,     when: mariadb_server }
