---
# handlers file for site_lamp
- name: Restart Apache
  service:
    name: "{{ service_apache }}"
    state: restarted
    enabled: true

- name: Restart MariaDB
  service:
    name: mariadb
    state: restarted
    enabled: true
...