---
# WEB SERVER

- name: install apache and php last version
  apt:
    name:
      - apache2
      - libapache2-mod-php7.4
      - php7.4-common
      - php7.4
      - php7.4-cli
      - php7.4-mysql
      - php7.4-curl
      - php7.4-gd
      - php7.4-intl
      - php7.4-memcache
      - php7.4-xml
      - php7.4-zip
      - php7.4-mbstring
      - php7.4-json
    state: present
    update_cache: yes

- name: Disable the Apache PHP module
  command: a2dismod php*
    state: absent
 
 - name: Disable the Apache PHP module
  command: a2enmod php7.4
    state: absent

- name: Give writable mode to http folder
  file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: upload web app source
  copy:
    src: '/role/lamp/files/skeletonigest01.tar.gz'
    dest: /var/www/html/
  
- name: ensure apache service is start
    service:
      name: apache2
      state: started
      enabled: yes


# DATABASE SERVER

- name: install mariadb-server
  apt: pkg={{ item }} state=latest
    name: 
      - mariadb-server
      - mariadb-client
      - mariadb-common
      - python-mysqldb # for mysql_db and mysql_user modules
    state: present
    update_cache: yes
 
 - name: ensure apache service is start
    service:
      name: mariadb
      state: started
      enabled: yes
   with_items:
 
 - name: Sets the root password
  mysql_user:
    name: root
    password: "{{ mysql_root_password }}"
    login_unix_socket: /var/run/mysqld/mariadb.sock

- name: Removes all anonymous user accounts
  mysql_user:
    name: ''
    host_all: yes
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Removes the Mariadb test database
  mysql_db:
    name: test
    state: absent
    login_user: root
    login_password: "{{ mysql_root_password }}"

- name: Create igest01_skeleton database
  mysql_db:
    name: igest01_skeleton
    login_user: root
    login_password: "{{ mysql_root_password }}"
    login_host: localhost
    state: present

- name: Restore database
  community.mysql.mysql_db:
    name: my_db
    state: import
    target: "/roles/lamp/file/dump.sql.bz2"
