---
# WEB SERVER

- name: install apache and php last version
  apt: pkg={{ item }} state=latest
    name:
      - apache2
      - php
      - php-cli
      - php-mysql
      - php-curl
      - php-gd
      - php-intl
      - php-memcache
      - php-xml
      - php-zip
      - php-mbstring
      - php-json
    state: present
    update_cache: yes

- name: Give writable mode to http folder
  file:
    path: /var/www/html
    state: directory
    mode: '0755'

- name: upload web app source
  copy:
    src: '/role/lamp/files/skeletonigest01.tar.gz'
    dest: /var/www/html/
  
- name: ensure apache service is start
    service:
      name: apache2
      state: started
      enabled: yes


# DATABASE SERVER

- name: install mariadb-server
  apt: pkg={{ item }} state=latest
    name: 
      - mariadb-server
      - python-mysqldb # for mysql_db and mysql_user modules
    state: present
    update_cache: yes
 
 - name: ensure apache service is start
    service:
      name: mariadb
      state: started
      enabled: yes

