- name: Update apt
  sudo: yes
  apt: update_cache=yes

- name: Purge php5 stuff
  shell: apt-get purge php5-fpm && apt-get -y --purge autoremove -y

    
- name: Add dependencies for PHP 7.4 versions (Debian).
  apt: pkg={{ item }} state=latest
    name:
      - apt-transport-https
      - ca-certificates
      - php7.4-imagick
      - php7.4-memcached
      - php7.4-redis
      - php7.4-xdebug
      - php7.4-bcmath
      - php7.4-bz2
      - php7.4-gd
      - php7.4-mbstring
      - php7.4-zip
      - php7.4-common
      - php7.4-intl
      - php7.4-mysql
      - php7.4-cli
      - php7.4-fpm
      - php7.4-json
      - php7.4-pdo
      - php7.4-curl
      - php7.4-xml
      - php7.4-tidy
      - php7.4-xmlrpc
      - php7.4-dev
      - php7.4-soap
      - php7.4-opcache
      - php7.4-ldap
      - php7.4-pgsql
      - php7.4-pspell
      - php7.4-recode
      - php7.4-snmp
      - php7.4-phpdbg
    state: present
