---
- block:
    - name: Install WHAT key for what software
      apt_key:
        url: http://keyserver.exemple.com/pks/lookup?op=get&search=0x{{ software.gpg_key_id }}
        state: present

    - name: Add repository to the software name
      apt_repository:
        repo: deb http://{{ software.mirror }}/softwaree/repo/{{ software.series_version }}/debian {{ debian.version }} main
        state: present
  when: ansible_distribution|lower == 'debian'

- name: Installer software name
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ liste_package_software }}"

- name: Start software
  service:
    name: mariadb
    state: started
    enabled: true
...